/**
 * HTTP transport envelope helpers.
 *
 * Maps application CommandResults to the HTTP success/error envelope contract
 * (§2.3, API-011). requestId is generated by the transport and echoed in the
 * X-Request-Id header.
 */
import type { ServerResponse, IncomingMessage } from "node:http";
import { randomUUID, createHash } from "node:crypto";
import { successEnvelope, errorEnvelope, ApplicationError } from "../contracts/envelope.ts";
import type { CommandResult } from "../application/shared/command.ts";
import { canonicalJsonStringify } from "../persistence/canonical-json.ts";

export { successEnvelope, errorEnvelope };

export function generateRequestId(): string {
  return randomUUID();
}

export function sendJson(
  res: ServerResponse,
  status: number,
  body: unknown,
  options?: { requestId?: string; extraHeaders?: Record<string, string>; etag?: string; cacheControl?: string; noStore?: boolean },
): void {
  const headers: Record<string, string> = { "Content-Type": "application/json" };
  if (options?.requestId) headers["X-Request-Id"] = options.requestId;
  if (options?.etag) headers.ETag = options.etag;
  if (options?.cacheControl) headers["Cache-Control"] = options.cacheControl;
  if (options?.noStore) headers["Cache-Control"] = "private, no-store";
  for (const [k, v] of Object.entries(options?.extraHeaders ?? {})) headers[k] = v;
  res.writeHead(status, headers);
  res.end(JSON.stringify(body));
}

export function sendError(
  res: ServerResponse,
  requestId: string,
  err: ApplicationError,
): void {
  sendJson(res, err.httpStatus, errorEnvelope(requestId, err.code, err.message, {
    fieldErrors: err.fieldErrors,
    diagnosticEvidenceArtifactId: err.diagnosticEvidenceArtifactId,
  }), { requestId });
}

export function sendApplicationError(
  res: ServerResponse,
  requestId: string,
  status: number,
  code: string,
  summary: string,
  fieldErrors: readonly { fieldPath: string; code: string; summary: string }[] = [],
): void {
  sendJson(res, status, errorEnvelope(requestId, code, summary, { fieldErrors }), { requestId });
}

export function sendCommandResult(
  res: ServerResponse,
  requestId: string,
  result: CommandResult<unknown>,
  dataBuilder?: () => unknown,
): void {
  if (result.kind === "executed") {
    sendJson(res, result.httpStatus, successEnvelope(requestId, dataBuilder ? dataBuilder() : result.data), { requestId });
    return;
  }
  if (result.kind === "replayed_success") {
    // Limited receipt: resource pointer only, no data/body.
    sendJson(res, result.httpStatus, successEnvelope(requestId, {
      commandType: "", // filled by caller if needed
      idempotencyRecordId: result.recordId,
      resultResourceType: result.resultResourceType,
      resultResourceId: result.resultResourceId,
      status: "succeeded",
    }), { requestId });
    return;
  }
  if (result.kind === "in_progress") {
    sendJson(res, 202, successEnvelope(requestId, {
      idempotencyRecordId: result.recordId,
      status: "in_progress",
      // statusUrl is intentionally omitted here; the caller should construct
      // the workspace-scoped URL from the request context.
    }), { requestId });
    return;
  }
  if (result.kind === "conflict") {
    sendJson(res, 409, errorEnvelope(requestId, "idempotency_key_reused", "This idempotency key has been used with a different request body.", {
      fieldErrors: [],
    }), { requestId });
    return;
  }
  sendJson(res, result.httpStatus, errorEnvelope(requestId, result.errorCode, result.errorSummary, {
    fieldErrors: result.fieldErrors,
  }), { requestId });
}

export function computeCanonicalDataEtag(data: unknown): string {
  const hash = createHash("sha256").update(canonicalJsonStringify(data), "utf8").digest("hex").slice(0, 32);
  return `"${hash}"`;
}

export function matchesEtag(req: IncomingMessage, etag: string): boolean {
  const raw = req.headers["if-none-match"];
  if (!raw) return false;
  return raw === etag || raw === `W/${etag}`;
}
