import assert from "node:assert/strict";
import { mkdtempSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";

process.env.XANTHIL_DATA_DIR = mkdtempSync(join(tmpdir(), "pi-xanthil-crowd-agg-"));

const db = await import("./db.ts");
const data = await import("./db/data.ts");
const { importAggregateDataset, autoTagDictionary, createDefaultSegment } = await import("./crowd-aggregate.ts");
const { normalizeEnumValue, normalizeRow } = await import("./crowd-normalize.ts");
const { computeFieldProfiles, computeTagDetailFieldProfiles, crowdFieldProfilesToLlmAggregateCsv } = await import("./crowd-import.ts");

const workspace = db.createWorkspace("test-aggregate");
const otherWs = db.createWorkspace("other-ws");

// ─── v2 wide-table fixture (matches demo-aggregate.csv structure) ──────────────

const V2_COLUMNS = [
  "segment_name",
  "dem_gender_female_pct", "dem_gender_male_pct",
  "dem_age_18_24_pct", "dem_age_25_34_pct", "dem_age_35_44_pct", "dem_age_45_54_pct", "dem_age_55_plus_pct",
  "dem_city_t1_pct", "dem_city_t1_new_pct", "dem_city_t2_pct", "dem_city_t3_pct", "dem_city_t4_plus_pct",
  "con_avg_monthly_spend",
  "pri_sens_high_pct", "pri_sens_mid_pct", "pri_sens_low_pct",
  "pri_dis_coupon_pct", "pri_dis_flash_sale_pct", "pri_dis_member_price_pct", "pri_dis_none_pct",
  "cha_top_channel",
  "lif_new_pct", "lif_active_pct", "lif_repeat_pct", "lif_dormant_pct", "lif_churned_pct",
  "sample_count",
];

const V2_ROWS = [
  { segment_name: "都市新锐女性", dem_gender_female_pct: 75, dem_gender_male_pct: 25, dem_age_18_24_pct: 38, dem_age_25_34_pct: 42, dem_age_35_44_pct: 15, dem_age_45_54_pct: 3, dem_age_55_plus_pct: 2, dem_city_t1_pct: 42, dem_city_t1_new_pct: 32, dem_city_t2_pct: 16, dem_city_t3_pct: 10, dem_city_t4_plus_pct: 0, con_avg_monthly_spend: 4200, pri_sens_high_pct: 22, pri_sens_mid_pct: 52, pri_sens_low_pct: 26, pri_dis_coupon_pct: 32, pri_dis_flash_sale_pct: 22, pri_dis_member_price_pct: 30, pri_dis_none_pct: 16, cha_top_channel: "小红书", lif_new_pct: 18, lif_active_pct: 52, lif_repeat_pct: 22, lif_dormant_pct: 6, lif_churned_pct: 2, sample_count: 40 },
  { segment_name: "下沉市场实用派", dem_gender_female_pct: 35, dem_gender_male_pct: 65, dem_age_18_24_pct: 15, dem_age_25_34_pct: 25, dem_age_35_44_pct: 32, dem_age_45_54_pct: 22, dem_age_55_plus_pct: 6, dem_city_t1_pct: 10, dem_city_t1_new_pct: 0, dem_city_t2_pct: 20, dem_city_t3_pct: 38, dem_city_t4_plus_pct: 32, con_avg_monthly_spend: 1850, pri_sens_high_pct: 58, pri_sens_mid_pct: 32, pri_sens_low_pct: 10, pri_dis_coupon_pct: 48, pri_dis_flash_sale_pct: 28, pri_dis_member_price_pct: 12, pri_dis_none_pct: 12, cha_top_channel: "线下门店", lif_new_pct: 8, lif_active_pct: 28, lif_repeat_pct: 38, lif_dormant_pct: 18, lif_churned_pct: 8, sample_count: 35 },
  { segment_name: "高净值成熟客", dem_gender_female_pct: 48, dem_gender_male_pct: 52, dem_age_18_24_pct: 3, dem_age_25_34_pct: 22, dem_age_35_44_pct: 48, dem_age_45_54_pct: 22, dem_age_55_plus_pct: 5, dem_city_t1_pct: 58, dem_city_t1_new_pct: 0, dem_city_t2_pct: 28, dem_city_t3_pct: 10, dem_city_t4_plus_pct: 4, con_avg_monthly_spend: 9200, pri_sens_high_pct: 8, pri_sens_mid_pct: 42, pri_sens_low_pct: 50, pri_dis_coupon_pct: 8, pri_dis_flash_sale_pct: 18, pri_dis_member_price_pct: 52, pri_dis_none_pct: 22, cha_top_channel: "天猫", lif_new_pct: 2, lif_active_pct: 32, lif_repeat_pct: 58, lif_dormant_pct: 6, lif_churned_pct: 2, sample_count: 25 },
];

// ─── importAggregateDataset (v2 wide-table) ────────────────────────────────────

test("importAggregateDataset creates dataset + N segments from v2 wide-table", () => {
  const result = importAggregateDataset(workspace.id, "v2-test", V2_COLUMNS, V2_ROWS);

  assert.ok(result.dataset.id);
  assert.equal(result.dataset.source, "aggregate_upload");
  assert.equal(result.dataset.isAggregate, true);
  assert.equal(result.dataset.fieldCount, 26); // 27 - segment_name = 26 data columns

  // Should create 3 segments (one per row)
  assert.equal(result.segments.length, 3, "one segment per row");
  assert.equal(result.segments[0]!.name, "都市新锐女性");
  assert.equal(result.segments[1]!.name, "下沉市场实用派");
  assert.equal(result.segments[2]!.name, "高净值成熟客");

  // All segments are autoGenerated
  for (const seg of result.segments) {
    assert.equal(seg.autoGenerated, true);
    assert.equal(seg.sampleCount > 0, true);
  }

  // Tag dictionary: one entry per data column
  assert.ok(result.tagDictionary.length > 0);
  for (const entry of result.tagDictionary) {
    assert.equal(entry.autoGenerated, true);
  }
});

test("importAggregateDataset rejects v1 long-table columns", () => {
  assert.throws(
    () => importAggregateDataset(workspace.id, "v1-bad", ["dimension", "field", "value"], []),
    /missing required v2 column: "segment_name"/,
  );
});

test("importAggregateDataset rejects missing v2 columns", () => {
  const incomplete = V2_COLUMNS.filter((c) => c !== "dem_age_25_34_pct");
  assert.throws(
    () => importAggregateDataset(workspace.id, "incomplete", incomplete, V2_ROWS),
    /missing required v2 column: "dem_age_25_34_pct"/,
  );
});

test("importAggregateDataset accepts BOM-prefixed segment_name header", () => {
  const columns = [`\uFEFF${V2_COLUMNS[0]}`, ...V2_COLUMNS.slice(1)];
  const rows = V2_ROWS.map((row) => {
    const { segment_name: segmentName, ...rest } = row;
    return { [`\uFEFFsegment_name`]: segmentName, ...rest };
  });
  const result = importAggregateDataset(workspace.id, "bom-v2", columns, rows);
  assert.equal(result.segments.length, V2_ROWS.length);
  assert.equal(result.segments[0]!.name, "都市新锐女性");
});

test("importAggregateDataset stores isAggregate in DB", () => {
  const { dataset } = importAggregateDataset(workspace.id, "isAgg-v2", V2_COLUMNS, V2_ROWS);
  const fetched = data.getCrowdDataset(dataset.id);
  assert.ok(fetched);
  assert.equal(fetched.isAggregate, true);
});

test("importAggregateDataset loads demo-aggregate.csv fixture", () => {
  const csvPath = join(process.cwd(), "server/static/crowd/demo-aggregate.csv");
  let csv: string;
  try {
    csv = readFileSync(csvPath, "utf-8");
  } catch {
    return; // skip if file not found (CI)
  }
  const lines = csv.trim().split("\n").filter((l) => l.trim());
  const columns = lines[0]!.split(",").map((c) => c.trim().replace(/^\uFEFF/, ""));
  const rows = lines.slice(1).map((line) => {
    const vals = line.split(",");
    const row: Record<string, unknown> = {};
    for (let i = 0; i < columns.length; i++) {
      const v = vals[i]?.trim() ?? "";
      row[columns[i]!] = isNaN(Number(v)) ? v : Number(v);
    }
    return row;
  });

  const result = importAggregateDataset(workspace.id, "demo-aggregate", columns, rows);
  assert.equal(result.segments.length, 6, "demo has 6 segments");
  assert.equal(result.segments[0]!.name, "都市新锐女性");
  assert.equal(result.segments[5]!.name, "家庭采购主力");
  assert.equal(result.dataset.fieldCount, 26);
});

// ─── autoTagDictionary (unchanged, still for detail channel) ───────────────────

test("autoTagDictionary generates heuristic dimension mapping", () => {
  const columns = ["age", "spend_amount", "interest_sports", "channel_source"];
  const rows = [
    { age: "25", spend_amount: "500", interest_sports: "是", channel_source: "微信" },
    { age: "30", spend_amount: "800", interest_sports: "否", channel_source: "抖音" },
  ];
  const fp = computeFieldProfiles({ columns, rows });
  const ds = data.createCrowdDataset(workspace.id, {
    name: "detail-ds",
    source: "upload_csv",
    rowCount: rows.length,
    fieldCount: columns.length,
    fieldProfiles: fp,
  });

  const entries = autoTagDictionary(workspace.id, ds.id);
  assert.equal(entries.length, 4);

  const ageEntry = entries.find((e) => e.field === "age");
  assert.ok(ageEntry);
  assert.equal(ageEntry.dimension, "demographic");

  const spendEntry = entries.find((e) => e.field === "spend_amount");
  assert.ok(spendEntry);
  assert.equal(spendEntry.dimension, "consumption_power");

  for (const e of entries) {
    assert.equal(e.autoGenerated, true);
  }
});

test("autoTagDictionary throws on non-existent dataset", () => {
  assert.throws(
    () => autoTagDictionary(workspace.id, "nonexistent-id"),
    /dataset not found/,
  );
});

test("autoTagDictionary throws on workspace mismatch", () => {
  const ds = data.createCrowdDataset(otherWs.id, { name: "x", source: "manual" });
  assert.throws(
    () => autoTagDictionary(workspace.id, ds.id),
    /belongs to another workspace/,
  );
});

test("computeTagDetailFieldProfiles applies type-level top rules and ignores tgi", () => {
  const rows = [
    { 标签类型: "电商品类", 标签: "裤装", 占比: "37.4%", tgi: 999 },
    { 标签类型: "电商品类", 标签: "T恤", 占比: "20%", tgi: 1 },
    { 标签类型: "电商品类", 标签: "卫衣", 占比: "10%", tgi: 1 },
    { 标签类型: "电商品类", 标签: "外套", 占比: "5%", tgi: 1 },
    { 标签类型: "城市", 标签: "二线城市", 占比: "12.4%", tgi: 888 },
    { 标签类型: "城市", 标签: "一线城市", 占比: "8%", tgi: 1 },
  ];
  const profiles = computeTagDetailFieldProfiles({ columns: ["标签类型", "标签", "占比", "tgi"], rows });
  assert.ok(profiles);
  const category = profiles.find((profile) => profile.field === "电商品类");
  const city = profiles.find((profile) => profile.field === "城市");
  assert.deepEqual(category?.topValues.map((value) => value.value), ["裤装", "T恤", "卫衣"]);
  assert.deepEqual(city?.topValues.map((value) => value.value), ["二线城市"]);
  assert.equal(category?.topValues[0]?.ratio, 0.374);
});

test("crowdFieldProfilesToLlmAggregateCsv exports only aggregate LLM input columns", () => {
  const rows = [
    { 标签类型: "电商品类", 标签: "裤装", 占比: "37.4%", tgi: 999 },
    { 标签类型: "电商品类", 标签: "T恤", 占比: "20%", tgi: 1 },
    { 标签类型: "电商品类", 标签: "卫衣", 占比: "10%", tgi: 1 },
    { 标签类型: "电商品类", 标签: "外套", 占比: "5%", tgi: 1 },
    { 标签类型: "城市", 标签: "二线城市", 占比: "12.4%", tgi: 888 },
    { 标签类型: "城市", 标签: "一线城市", 占比: "8%", tgi: 1 },
  ];
  const profiles = computeTagDetailFieldProfiles({ columns: ["标签类型", "标签", "占比", "tgi"], rows });
  assert.ok(profiles);
  const csv = crowdFieldProfilesToLlmAggregateCsv(profiles);
  assert.equal(csv.split("\n")[0], "标签类型,标签,占比");
  assert.match(csv, /电商品类,裤装,37.4%/);
  assert.match(csv, /城市,二线城市,12.4%/);
  assert.doesNotMatch(csv, /tgi/i);
  assert.doesNotMatch(csv, /外套/);
});

// ─── createDefaultSegment ───────────────────────────────────────────────────────

test("createDefaultSegment creates unconditional full-sample segment", () => {
  const { dataset } = importAggregateDataset(workspace.id, "seg-test", V2_COLUMNS, V2_ROWS);
  const segment = createDefaultSegment(workspace.id, dataset.id);
  assert.equal(segment.name, "全样本（自动）");
  assert.equal(segment.autoGenerated, true);
  assert.deepEqual(segment.rule, { logic: "and", conditions: [] });
  assert.equal(segment.sampleCount, dataset.rowCount);
  assert.equal(segment.coverageRatio, 1);
  assert.ok(Object.keys(segment.tagDistribution).length > 0);
});

test("createDefaultSegment throws on non-existent dataset", () => {
  assert.throws(
    () => createDefaultSegment(workspace.id, "nonexistent"),
    /dataset not found/,
  );
});

test("createDefaultSegment throws on workspace mismatch", () => {
  const ds = data.createCrowdDataset(otherWs.id, { name: "x", source: "manual" });
  assert.throws(
    () => createDefaultSegment(workspace.id, ds.id),
    /belongs to another workspace/,
  );
});

// ─── DB persistence ─────────────────────────────────────────────────────────────

test("tag dictionary autoGenerated persisted in DB", () => {
  const { dataset, tagDictionary } = importAggregateDataset(workspace.id, "persist-v2", V2_COLUMNS, V2_ROWS);
  const fetched = data.listCrowdTagDictionary(workspace.id, dataset.id);
  assert.equal(fetched.length, tagDictionary.length);
  for (const e of fetched) {
    assert.equal(e.autoGenerated, true);
  }
});

test("segments autoGenerated persisted in DB", () => {
  const { dataset } = importAggregateDataset(workspace.id, "seg-persist-v2", V2_COLUMNS, V2_ROWS);
  const segments = data.listCrowdSegments(workspace.id, dataset.id);
  const autoSegs = segments.filter((s) => s.autoGenerated === true);
  assert.equal(autoSegs.length, 3);
});

// ─── R2: normalization layer ────────────────────────────────────────────────────

test("normalizeEnumValue: Chinese gender → English", () => {
  assert.deepEqual(normalizeEnumValue("gender", "女"), { normalized: "F", failed: false });
  assert.deepEqual(normalizeEnumValue("gender", "男"), { normalized: "M", failed: false });
  assert.deepEqual(normalizeEnumValue("gender", "其他"), { normalized: "O", failed: false });
});

test("normalizeEnumValue: Chinese city tier → English", () => {
  assert.deepEqual(normalizeEnumValue("city_tier", "一线"), { normalized: "T1", failed: false });
  assert.deepEqual(normalizeEnumValue("city_tier", "新一线"), { normalized: "T1_NEW", failed: false });
  assert.deepEqual(normalizeEnumValue("city_tier", "四线及以下"), { normalized: "T4_PLUS", failed: false });
});

test("normalizeEnumValue: Chinese channel → English", () => {
  assert.deepEqual(normalizeEnumValue("preferred_channel", "小红书"), { normalized: "xhs", failed: false });
  assert.deepEqual(normalizeEnumValue("preferred_channel", "抖音"), { normalized: "douyin", failed: false });
  assert.deepEqual(normalizeEnumValue("preferred_channel", "线下门店"), { normalized: "offline", failed: false });
});

test("normalizeEnumValue: Chinese lifecycle → English", () => {
  assert.deepEqual(normalizeEnumValue("lifecycle_stage", "流失"), { normalized: "churned", failed: false });
  assert.deepEqual(normalizeEnumValue("lifecycle_stage", "新客"), { normalized: "new", failed: false });
  assert.deepEqual(normalizeEnumValue("lifecycle_stage", "活跃"), { normalized: "active", failed: false });
});

test("normalizeEnumValue: unknown value → normalizationFailed", () => {
  const r = normalizeEnumValue("gender", "未知性别");
  assert.equal(r.normalized, "未知性别");
  assert.equal(r.failed, true);
});

test("normalizeEnumValue: slash-separated multi-values", () => {
  const r = normalizeEnumValue("scenario_top2", "周末出游/自我犒赏");
  assert.equal(r.normalized, "weekend_outing/self_reward");
  assert.equal(r.failed, false);
});

test("normalizeEnumValue: slash-separated with unknown part", () => {
  const r = normalizeEnumValue("scenario_top2", "周末出游/未知场景");
  assert.equal(r.normalized, "weekend_outing/未知场景");
  assert.equal(r.failed, true);
});

test("normalizeRow: full row normalization", () => {
  const columns = ["gender", "city_tier", "lifecycle_stage"];
  const row = { gender: "女", city_tier: "新一线", lifecycle_stage: "流失" };
  const result = normalizeRow(columns, row);
  assert.equal(result.values.gender, "F");
  assert.equal(result.values.city_tier, "T1_NEW");
  assert.equal(result.values.lifecycle_stage, "churned");
  assert.equal(result.failedFields.length, 0);
});

test("normalizeRow: tracks failed fields", () => {
  const columns = ["gender", "custom_field"];
  const row = { gender: "女", custom_field: "some_value" };
  const result = normalizeRow(columns, row);
  assert.equal(result.values.gender, "F");
  assert.equal(result.values.custom_field, "some_value"); // pass-through, not failed
  assert.equal(result.failedFields.length, 0);
});

test("normalizeEnumValue: empty string → not failed", () => {
  assert.deepEqual(normalizeEnumValue("gender", ""), { normalized: "", failed: false });
});

test("E2E: demo-detail.csv → computeFieldProfiles(normalizeEnums:true) → English enums", () => {
  const csvPath = join(process.cwd(), "server/static/crowd/demo-detail.csv");
  let csv: string;
  try {
    csv = readFileSync(csvPath, "utf-8");
  } catch {
    return; // skip if file not found (CI)
  }
  const lines = csv.trim().split("\n").filter((l) => l.trim());
  const columns = lines[0]!.split(",").map((c) => c.trim().replace(/^\uFEFF/, ""));
  const rows = lines.slice(1).map((line) => {
    const vals = line.split(",");
    const row: Record<string, unknown> = {};
    for (let i = 0; i < columns.length; i++) {
      row[columns[i]!] = vals[i]?.trim() ?? "";
    }
    return row;
  });

  const fp = computeFieldProfiles({ columns, rows, normalizeEnums: true });

  const genderFp = fp.find((p) => p.field === "gender")!;
  const genderValues = genderFp.topValues.map((v) => v.value);
  assert.ok(genderValues.includes("F"), "gender contains F");
  assert.ok(genderValues.includes("M"), "gender contains M");
  assert.ok(genderValues.includes("O"), "gender contains O");
  assert.ok(!genderValues.some((v) => /[男女其他]/.test(v)), "gender has no Chinese values");

  const cityFp = fp.find((p) => p.field === "city_tier")!;
  const cityValues = cityFp.topValues.map((v) => v.value);
  assert.ok(cityValues.includes("T1"), "city_tier contains T1");
  assert.ok(cityValues.includes("T1_NEW"), "city_tier contains T1_NEW");
  assert.ok(!cityValues.some((v) => /线/.test(v)), "city_tier has no Chinese values");

  const channelFp = fp.find((p) => p.field === "preferred_channel")!;
  const channelValues = channelFp.topValues.map((v) => v.value);
  assert.ok(channelValues.includes("xhs"), "channel contains xhs");
  assert.ok(channelValues.includes("wechat_mp"), "channel contains wechat_mp");
  assert.ok(!channelValues.some((v) => /[小红书抖音微信天猫京东线下]/.test(v)), "channel has no Chinese values");

  const lifecycleFp = fp.find((p) => p.field === "lifecycle_stage")!;
  const lifecycleValues = lifecycleFp.topValues.map((v) => v.value);
  assert.ok(lifecycleValues.includes("churned"), "lifecycle contains churned");
  assert.ok(lifecycleValues.includes("active"), "lifecycle contains active");
  assert.ok(!lifecycleValues.some((v) => /[新客活跃复购沉睡流失]/.test(v)), "lifecycle has no Chinese values");
});
