// X-CROWD12 全链验收 smoke · 总控自做卡 · 2026-06-29
// 验收范围：
//   1. D-CROWD10 模板/示例下载 + CSV 内容契约
//   2. E-CROWD11 聚合通道（v2 27 列宽表 → N segment）+ 自动字典 + 默认分群 + 中→英归一化
//   3. D-CROWD11 一键画像工作流（明细 4 步 / 聚合 2 步）
//   4. 与既有 generateCrowdProfile（E-CROWD5）链路兼容
//   5. 安全口径：LLM prompt 不含 raw rows / 字段值样本 / 原始明细

import assert from "node:assert/strict";
import { mkdtempSync, readFileSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import test from "node:test";

process.env.XANTHIL_DATA_DIR = mkdtempSync(join(tmpdir(), "pi-xanthil-x-crowd12-"));

const __dirname = dirname(fileURLToPath(import.meta.url));
const CROWD_STATIC_ROOT = join(__dirname, "..", "static", "crowd");

const db = await import("./db.ts");
const data = await import("./db/data.ts");
const { computeFieldProfiles } = await import("./crowd-import.ts");
const { importAggregateDataset, autoTagDictionary, createDefaultSegment } = await import("./crowd-aggregate.ts");
const { runCrowdProfileGeneration } = await import("./crowd-profile-runner.ts");

function parseCsv(filePath: string): { columns: string[]; rows: Record<string, unknown>[] } {
  const csv = readFileSync(filePath, "utf-8");
  const lines = csv.trim().split("\n").filter((l) => l.trim());
  const columns = lines[0]!.split(",").map((c) => c.trim().replace(/^\uFEFF/, ""));
  const rows = lines.slice(1).map((line) => {
    const vals = line.split(",");
    const row: Record<string, unknown> = {};
    for (let i = 0; i < columns.length; i++) {
      const v = vals[i]?.trim() ?? "";
      row[columns[i]!] = isNaN(Number(v)) || v === "" ? v : Number(v);
    }
    return row;
  });
  return { columns, rows };
}

test("X-CROWD12 · D-CROWD10 模板文件契约：4 文件均存在 + BOM + 列结构", () => {
  const root = CROWD_STATIC_ROOT;
  for (const name of ["template-detail.csv", "template-aggregate.csv", "demo-detail.csv", "demo-aggregate.csv"]) {
    const p = join(root, name);
    assert.ok(existsSync(p), `${name} exists`);
    const buf = readFileSync(p);
    assert.equal(buf[0], 0xef, `${name} BOM byte 0`);
    assert.equal(buf[1], 0xbb, `${name} BOM byte 1`);
    assert.equal(buf[2], 0xbf, `${name} BOM byte 2`);
  }

  const detail = parseCsv(join(root, "template-detail.csv"));
  assert.deepEqual(detail.columns, [
    "gender", "age_bracket", "city_tier", "avg_monthly_spend", "price_sensitivity_level",
    "interest_top3", "preferred_channel", "discount_response", "lifecycle_stage", "scenario_top2",
  ]);

  const agg = parseCsv(join(root, "template-aggregate.csv"));
  assert.equal(agg.columns.length, 28, "aggregate 28 cols (segment_name + 26 data + sample_count)");
  assert.equal(agg.columns[0], "segment_name");
  assert.equal(agg.columns[agg.columns.length - 1]!, "sample_count");
});

test("X-CROWD12 · D-CROWD10 demo-detail 40 行虚拟数据 + 各字段 ≥2 个枚举", () => {
  const { columns, rows } = parseCsv(join(CROWD_STATIC_ROOT, "demo-detail.csv"));
  assert.equal(rows.length, 40);
  assert.equal(columns.length, 10);
  for (const col of columns) {
    const unique = new Set(rows.map((r) => r[col]));
    assert.ok(unique.size >= 2, `${col} has >= 2 unique values, got ${unique.size}`);
  }
});

test("X-CROWD12 · E-CROWD11 R5 归一化层接入：demo-detail.csv → 入库英文枚举", () => {
  const { columns, rows } = parseCsv(join(CROWD_STATIC_ROOT, "demo-detail.csv"));
  const fp = computeFieldProfiles({ columns, rows, normalizeEnums: true });

  const gender = fp.find((p) => p.field === "gender")!;
  for (const tv of gender.topValues) {
    assert.ok(["F", "M", "O"].includes(tv.value), `gender 入库英文: ${tv.value}`);
  }

  const channel = fp.find((p) => p.field === "preferred_channel")!;
  for (const tv of channel.topValues) {
    assert.ok(/^[a-z_]+$/.test(tv.value), `channel 入库英文: ${tv.value}`);
  }

  const lifecycle = fp.find((p) => p.field === "lifecycle_stage")!;
  for (const tv of lifecycle.topValues) {
    assert.ok(["new", "active", "repeat", "dormant", "churned"].includes(tv.value), `lifecycle: ${tv.value}`);
  }
});

test("X-CROWD12 · E-CROWD11 聚合通道：demo-aggregate.csv → 6 个 CrowdSegment", () => {
  const workspace = db.createWorkspace("x-crowd12-agg");
  const { columns, rows } = parseCsv(join(CROWD_STATIC_ROOT, "demo-aggregate.csv"));

  const result = importAggregateDataset(workspace.id, "demo-agg", columns, rows);
  assert.equal(result.dataset.isAggregate, true);
  assert.equal(result.dataset.source, "aggregate_upload");
  assert.equal(result.segments.length, 6, "demo-aggregate.csv 6 行 → 6 segments");

  for (const seg of result.segments) {
    assert.equal(seg.autoGenerated, true);
    assert.ok(seg.sampleCount > 0, `${seg.name} sampleCount > 0`);
  }

  assert.ok(result.tagDictionary.length > 0);
  for (const entry of result.tagDictionary) {
    assert.equal(entry.autoGenerated, true);
  }
});

test("X-CROWD12 · D-CROWD11 明细 4 步链路 + 安全审计 prompt 不含 raw rows", async () => {
  const workspace = db.createWorkspace("x-crowd12-detail");
  const { columns, rows } = parseCsv(join(CROWD_STATIC_ROOT, "demo-detail.csv"));

  const fp = computeFieldProfiles({ columns, rows, normalizeEnums: true });
  const dataset = data.createCrowdDataset(workspace.id, {
    name: "demo-detail", source: "upload_csv", rowCount: rows.length, fieldCount: columns.length, fieldProfiles: fp,
  });

  const dict = autoTagDictionary(workspace.id, dataset.id);
  assert.equal(dict.length, columns.length);

  const seg = createDefaultSegment(workspace.id, dataset.id);
  assert.equal(seg.name, "全样本（自动）");

  let capturedPrompt = "";
  const result = await runCrowdProfileGeneration(
    { segmentId: seg.id, model: "ep-smoke", businessContext: "" },
    {
      workspaceId: workspace.id,
      runPi: async ({ text }) => {
        capturedPrompt = text;
        return JSON.stringify({
          traits: ["t"], motivations: ["m"], decisionTriggers: ["d"], objections: ["o"],
          tone: "neutral", contentPreference: ["c"], riskNotes: ["r"], evidenceSummary: ["e"], persona: "p",
        });
      },
    },
  );
  assert.equal(result.profile.segmentId, seg.id);

  // 安全：prompt 不能含 PII / raw row 标识符
  for (const evil of ["user_id", "phone", "email", "openid", "unionid", "身份证", "手机号"]) {
    assert.ok(!capturedPrompt.includes(evil), `prompt 不含 PII 标记: "${evil}"`);
  }
});

test("X-CROWD12 · 聚合通道 generateProfile prompt 仅含聚合摘要不含明细", async () => {
  const workspace = db.createWorkspace("x-crowd12-sec");
  const { columns, rows } = parseCsv(join(CROWD_STATIC_ROOT, "demo-aggregate.csv"));
  const result = importAggregateDataset(workspace.id, "sec-agg", columns, rows);

  const seg = result.segments[0]!;
  let capturedPrompt = "";
  await runCrowdProfileGeneration(
    { segmentId: seg.id, model: "ep-smoke", businessContext: "" },
    {
      workspaceId: workspace.id,
      runPi: async ({ text }) => {
        capturedPrompt = text;
        return JSON.stringify({
          traits: ["x"], motivations: ["x"], decisionTriggers: ["x"], objections: ["x"],
          tone: "x", contentPreference: ["x"], riskNotes: ["x"], evidenceSummary: ["x"], persona: "x",
        });
      },
    },
  );

  assert.ok(!capturedPrompt.includes("user_id"), "prompt 不含 user_id");
  assert.ok(!capturedPrompt.includes("phone"), "prompt 不含 phone");
  assert.ok(capturedPrompt.length > 100, "prompt 仍然包含聚合统计字段信息（非空）");
});
