import type { WorkflowDef } from "./multi-agent-runner.ts";

export const RUN_SQL_QUERY_TOOL_ID = "run-sql-query" as const;

export function buildSqlLoopWorkflow(): WorkflowDef {
  return {
    version: 1,
    layout: "dag",
    nodes: [
      {
        id: "plan",
        label: "P·SQL 分析计划",
        role: "数据分析规划师",
        spec: "01-sql-plan.md",
        prompt: [
          "你是一位数据分析规划师。请根据任务和可用 schema 制定 SQL 分析计划。",
          "",
          "任务描述：{{input.task}}",
          "SQL 连接 ID：{{input.sql_connection_id}}",
          "关键字段要求：{{input.required_fields}}",
          "可用 schema / 口径说明：",
          "{{input.schema_context}}",
          "",
          "请输出：",
          "1. 分析目标和成功标准",
          "2. 需要查询的表、字段、过滤条件和聚合口径",
          "3. 预期返回字段，必须覆盖关键字段要求",
          "4. SQL 生成注意事项",
        ].join("\n"),
      },
      {
        id: "sql",
        label: "S·生成 SQL",
        role: "SQL 工程师",
        spec: "02-query.sql.md",
        inputs: ["plan"],
        prompt: [
          "你是一位谨慎的 SQL 工程师。请根据分析计划生成一条只读 SELECT SQL。",
          "",
          "分析计划：",
          "{{plan}}",
          "",
          "上一轮 SQL 错误反馈（如为空表示首轮生成）：",
          "{{sql_error}}",
          "",
          "约束：",
          "- 只能输出只读 SELECT / WITH 查询，禁止 DROP/DELETE/UPDATE/INSERT/ALTER/CREATE 等写操作",
          "- 必须显式选择字段，避免 SELECT *",
          "- 必须返回关键字段：{{input.required_fields}}",
          "- 如果存在上一轮错误反馈，只修复失败部分，不改变原业务逻辑、指标口径和筛选意图",
          "- 保持 SQL 与任务目标一致：{{input.task}}",
          "",
          "请在回复末尾输出唯一 SQL 块：",
          "```sql",
          "SELECT ...",
          "```",
        ].join("\n"),
      },
      {
        id: "run_sql",
        label: "T·执行 SQL",
        prompt: "Run generated SQL",
        kind: "tool",
        toolId: RUN_SQL_QUERY_TOOL_ID,
        inputPath: "{{sql}}",
        outputDir: "sql-output",
        timeoutMs: 60_000,
        inputs: ["sql"],
      },
      {
        id: "sql_gate",
        label: "G·SQL 结果门禁",
        role: "SQL 结果门禁",
        kind: "gate",
        inputs: ["run_sql"],
        onBlock: { retryFromNodeId: "sql", maxIterations: 5, feedbackVar: "sql_error" },
        prompt: [
          "系统将基于 run_sql 的结构化输出执行确定性门禁：",
          "- SQL 执行码必须为 0",
          "- 查询结果必须非空",
          "- 结果 columns 必须包含关键字段",
          "",
          "run_sql 输出：",
          "{{run_sql}}",
        ].join("\n"),
      },
    ],
    edges: [
      { id: "e-plan-sql", source: "plan", target: "sql" },
      { id: "e-sql-run_sql", source: "sql", target: "run_sql" },
      { id: "e-run_sql-sql_gate", source: "run_sql", target: "sql_gate" },
    ],
  };
}
